apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: v1lis0ubl-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: v1lis0ubl-python 
  name: v1lis0ubl-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: v1lis0ubl-python 
